In [1]:
! [ -e /content ] && pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

In [3]:
from fastai.vision.all import *
from fastbook import *

In [10]:
#time = torch.arange(0,20).float();
#speed = torch.randn(20)*3 + 0.75*(time-9.5)**2 + 1
#plt.scatter(time,speed);

In [11]:
#time, speed

In [21]:
time = torch.arange(0,20).float();
speed = torch.randn(20)*3 + 0.75*(time-9.5)**2 + 1
params = tensor([-1.3392, -1.3702, -0.3218], requires_grad=True)

def f(t, params):
    a,b,c = params
    return a*(t**2) + (b*t) + c

def mse(preds, targets): return ((preds-targets)**2).mean()

preds = f(time, params)
loss = mse(preds, speed)

In [30]:
# loss.backward()
# how can we calculate this?


In [22]:
params, time, speed, preds, loss

(tensor([-1.3392, -1.3702, -0.3218], requires_grad=True),
 tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]),
 tensor([67.7380, 56.9534, 40.5161, 33.9169, 29.4810, 19.2231,  5.8783,  2.2979,  2.2794,  6.0937,  3.1517,  4.4155,  9.1120, 10.2432, 10.7701, 26.4638, 31.5615, 46.2868, 53.1275, 70.5979]),
 tensor([-3.2180e-01, -3.0312e+00, -8.4190e+00, -1.6485e+01, -2.7230e+01, -4.0653e+01, -5.6754e+01, -7.5534e+01, -9.6992e+01, -1.2113e+02, -1.4794e+02, -1.7744e+02, -2.0961e+02, -2.4446e+02,
         -2.8199e+02, -3.2219e+02, -3.6508e+02, -4.1064e+02, -4.5889e+02, -5.0981e+02], grad_fn=<AddBackward0>),
 tensor(69850.4141, grad_fn=<MeanBackward0>))

In [27]:
# def show_preds(preds, ax=None):
#     if ax is None: ax=plt.subplots()[1]
#     ax.scatter(time, speed)
#     ax.scatter(time, to_np(preds), color='red')
#     ax.set_ylim(-300,100)

In [29]:
# show_preds(preds)

In [28]:
# loss.backward()
# params.grad